import { useState, useEffect } from 'react'

import './Popup.css'

export const Popup = () => {
  const [count, setCount] = useState(0)
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const minus = () => {
    if (count > 0) setCount(count - 1)
  }

  const add = () => setCount(count + 1)

  useEffect(() => {
    chrome.storage.sync.get(['count'], (result) => {
      setCount(result.count || 0)
    })
  }, [])

  useEffect(() => {
    chrome.storage.sync.set({ count })
    chrome.runtime.sendMessage({ type: 'COUNT', count })
  }, [count])

  useEffect(() => {
    console.log('env', import.meta.env)
  }, [])

  return (
    <main className="flex-col justify-center items-center flex mt-10 space-x-3">
      <h3 className="text-blue-500 uppercase font-normal m-auto">Popup Page</h3>
      <div className=" flex flex-row items-center justify-center gap-2">
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline border-blue-500 border-1"
          onClick={minus}
          disabled={count <= 0}
        >
          -
        </button>
        <label>{count}</label>
        <button
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline border-blue-500 border-1"
          onClick={add}
        >
          +
        </button>
      </div>
      <a
        className="text-sm m-4 text-gray-300 hover:underline cursor-pointer underline-offset-2"
        href={link}
        target="_blank"
      >
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default Popup
