name: Build

on:
  push:
    branches: ['main', 'feat/*']

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: install dependency
        run: yarn
      - name: Create chrome artifacts
        run: yarn zip
      - name: Create Firefox artifacts
        run: yarn zip:firefox
      - uses: actions/upload-artifact@v4
        with:
          name: zip-extensions
          path: |
            package/*
