name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: install dependency
        run: yarn
      - name: Create chrome artifacts
        run: yarn zip
      - name: Create Firefox artifacts
        run: yarn zip:firefox

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: 'COMMIT'
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: ${{steps.github_release.outputs.changelog}}
          files: ./package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

