name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: 'COMMIT'
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: zip-extensions
          path: ./package
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          files: ./package/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

